[2024-06-12T07:11:39.462+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-12T07:11:39.897+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_final_dag.create_table scheduled__2024-06-09T08:20:00+00:00 [queued]>
[2024-06-12T07:11:39.929+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_final_dag.create_table scheduled__2024-06-09T08:20:00+00:00 [queued]>
[2024-06-12T07:11:39.930+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-12T07:11:40.189+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): create_table> on 2024-06-09 08:20:00+00:00
[2024-06-12T07:11:40.207+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=233) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-12T07:11:40.211+0000] {standard_task_runner.py:63} INFO - Started process 264 to run task
[2024-06-12T07:11:40.284+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'spotify_final_dag', 'create_table', 'scheduled__2024-06-09T08:20:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/spotify_final_dag.py', '--cfg-path', '/tmp/tmp4hd9b_sm']
[2024-06-12T07:11:40.287+0000] {standard_task_runner.py:91} INFO - Job 31: Subtask create_table
[2024-06-12T07:11:41.806+0000] {task_command.py:426} INFO - Running <TaskInstance: spotify_final_dag.create_table scheduled__2024-06-09T08:20:00+00:00 [running]> on host d317f063dba7
[2024-06-12T07:11:45.538+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spotify_final_dag' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-06-09T08:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-09T08:20:00+00:00'
[2024-06-12T07:11:45.545+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-12T07:11:45.547+0000] {sql.py:276} INFO - Executing: 
	CREATE TABLE IF NOT EXISTS my_played_tracks(
	song_name VARCHAR(200),
	artist_name VARCHAR(200),
	played_at VARCHAR(200),
	timestamp VARCHAR(200),
	CONSTRAINT primary_key_constraint PRIMARY KEY (played_at)
	)
        
[2024-06-12T07:11:45.585+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-12T07:11:45.615+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 277, in execute
    hook = self.get_db_hook()
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 188, in get_db_hook
    return self._hook
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 150, in _hook
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgre_sql` isn't defined
[2024-06-12T07:11:45.656+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=spotify_final_dag, task_id=create_table, run_id=scheduled__2024-06-09T08:20:00+00:00, execution_date=20240609T082000, start_date=20240612T071139, end_date=20240612T071145
[2024-06-12T07:11:45.859+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 31 for task create_table (The conn_id `postgre_sql` isn't defined; 264)
[2024-06-12T07:11:46.120+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-12T07:11:46.224+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
